### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by rafa19** [Cleveroad/slidingtutorial-android#40]
Hi I am getting this error.

``` java
Exception in MessageQueue callback: handleReceiveCallback
java.lang.NullPointerException: Attempt to read from field 'int android.view.View.mViewFlags' on a null object reference
     at android.view.ViewGroup.canViewReceivePointerEvents(ViewGroup.java:2317)
     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2035)
     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2050)
     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2050)
     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2050)
     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2050)
     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2050)
     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2050)
     at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2625)
     at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1770)
     at android.app.Activity.dispatchTouchEvent(Activity.java:2742)
     at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2586)
     at android.view.View.dispatchPointerEvent(View.java:8675)
     at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4129)
     at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3995)
     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3550)
     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3603)
     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3569)
     at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3686)
     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3577)
     at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3743)
     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3550)
     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3603)
     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3569)
     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3577)
     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3550)
     at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5813)
     at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5787)
     at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5758)
     at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5903)
     at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
     at android.os.MessageQueue.nativePollOnce(Native Method)
     at android.os.MessageQueue.next(MessageQueue.java:143)
     at android.os.Looper.loop(Looper.java:122)
     at android.app.ActivityThread.main(ActivityThread.java:5294)
     at java.lang.reflect.Method.invoke(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:372)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

**Comment by Iojjj** [comment]
Hi @rafa19,

could you tell me the steps how to reproduce this issue? The stacktrace doesn't give any clue for this.

**Comment by rafa19** [comment]
This happens when I scroll quickly.

**Comment by Iojjj** [comment]
It seems this crash happens when fragment was removed from screen and fragment manager, but system tries to do something with fragment's view.

Are you getting this crash with infinite loop or with auto-removing of empty fragment? If second option: are you catting this crash after tutorial finished?

**Comment by VadimHalimendikCr** [comment]
Hello! We fixed this bug in the latest version of this library.
Best regards Cleveroad team.
