### ISSUE TITLE
Exception in ViewPager

### ISSUE THREAD

**Issue by JackyDuong** [Cleveroad/slidingtutorial-android#47]
Hi !

I found a bug when you swipe fast between the view 0 and 1 or N and N-1. It seems that the ViewPager change the size of the list of pages from 3 to 2 when the ViewPager is at position 0 and N.
If you switch fast to position 1, it's like ViewPager has a size of 2 in extremity then it tries to access to the position 2 (load the neighboor pages) and crashes.

There is the exception : 

```
11-16 17:43:13.121 19447-19447/ch.gookers.buyer E/InputEventReceiver: Exception dispatching input event.
11-16 17:43:13.131 19447-19447/ch.gookers.buyer E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
11-16 17:43:13.151 19447-19447/ch.gookers.buyer E/MessageQueue-JNI: java.lang.IndexOutOfBoundsException: Invalid index 2, size is 2
at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
at java.util.ArrayList.get(ArrayList.java:308)
at android.support.v4.view.ViewPager.getChildDrawingOrder(ViewPager.java:832)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2424)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2456)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2456)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2456)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2456)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2456)
at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2831)
at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1863)
at android.app.Activity.dispatchTouchEvent(Activity.java:3046)
at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2792)
at android.view.View.dispatchPointerEvent(View.java:10228)
at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5344)
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5180)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4620)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4673)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4639)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4781)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4647)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4838)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4620)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4673)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4639)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4647)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4620)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7306)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7184)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7145)
at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7416)
at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:323)
at android.os.Looper.loop(Looper.java:143)
at android.app.ActivityThread.main(ActivityThread.java:7224)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

```

My values in array.xml 

```    <string-array name="boarding_title">
        <item>@string/boarding_title_1</item>
        <item>@string/boarding_title_2</item>
        <item>@string/boarding_title_3</item>
        <item>@string/boarding_title_4</item>
    </string-array>
    <string-array name="boarding_text">
        <item>@string/boarding_text_1</item>
        <item>@string/boarding_text_2</item>
        <item>@string/boarding_text_3</item>
        <item>@string/boarding_text_4</item>
    </string-array>
    <integer-array name="boarding_picture">
        <item>@drawable/boarding_1</item>
        <item>@drawable/boarding_2</item>
        <item>@drawable/boarding_3</item>
        <item>@drawable/boarding_4</item>
    </integer-array>
```

My tutorial fragment

```
public class BoardingTutorialFragment extends TutorialFragment {

    private static final int TOTAL_PAGES = 4;
    private Map<Integer, Fragment> fragments = new HashMap<>();

    private final TutorialPageProvider<Fragment> mTutorialPageProvider = new TutorialPageProvider<Fragment>() {
        @NonNull
        @Override
        public Fragment providePage(int position) {
            if (fragments.get(Integer.valueOf(position)) == null)
                fragments.put(Integer.valueOf(position), BoardingFragment.getFragment(position));
            return fragments.get(Integer.valueOf(position));
        }
    };

    @Override
    protected TutorialOptions provideTutorialOptions() {
        return newTutorialOptionsBuilder(this.getActivity())
                .setPagesCount(TOTAL_PAGES)
                .setTutorialPageProvider(mTutorialPageProvider)
                .build();
    }
}
```
My page fragment

```
public class BoardingFragment extends PageFragment {
    private static final String TAG = "BoardingFragment";
    private static final String POSITION = "ch.gookers.buyer.views.boarding.position";

    private int position = 0;

    @BindView(R.id.boarding_image)
    protected ImageView ivImage;

    @BindView(R.id.boarding_title)
    protected TextView tvTitle;

    @BindView(R.id.boarding_text)
    protected TextView tvText;

    public static Fragment getFragment(int position) {
        Fragment fragment = new BoardingFragment();
        Bundle args = new Bundle();
        args.putInt(POSITION, position);
        fragment.setArguments(args);
        return fragment;
    }

    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Bundle args = getArguments();
        if (args != null)
            position = args.getInt(POSITION);
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        ButterKnife.bind(this, view);
        setImage();
        setTitle();
        setText();
        Log.d(TAG, "VIEW CREATED");
    }

    private void setImage(){
        TypedArray pictures = getResources().obtainTypedArray(R.array.boarding_picture);
        Picasso.with(getActivity()).load(pictures.getResourceId(position, -1)).into(ivImage);
        pictures.recycle();
    }

    private void setTitle(){
        Log.d(TAG, "Position = "+position);
        String[] titles = getResources().getStringArray(R.array.boarding_title);
        Log.d(TAG, "titles size = "+titles.length);
        tvTitle.setText(titles[position]);
    }

    private void setText(){
        Log.d(TAG, "Position = "+position);
        String[] texts = getResources().getStringArray(R.array.boarding_text);
        Log.d(TAG, "texts size = "+texts.length);
        tvText.setText(texts[position]);
    }

    @Override
    protected int getLayoutResId() {
        Log.d(TAG, "getLayoutResId");
        return R.layout.boarding_fragment_layout;
    }

    @NonNull
    @Override
    protected TransformItem[] getTransformItems() {
        return new TransformItem[]{
                // TransformItem.create(view for transform, moving direction, shift coefficient)
                TransformItem.create(R.id.boarding_image, Direction.LEFT_TO_RIGHT, 0),
                TransformItem.create(R.id.boarding_title, Direction.LEFT_TO_RIGHT, 0),
                TransformItem.create(R.id.boarding_text, Direction.LEFT_TO_RIGHT, 0)
        };
    }
}
```

**Comment by VadimHalimendikCr** [comment]
Hi!  We will fix this error in the next version of this library.
With best regards Cleveroad team.
