### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Invalid index 2, size is 2

### ISSUE THREAD

**Issue by louisyonge** [Cleveroad/slidingtutorial-android#55]
I am using Android studio 2.3, Sliding Tutuorial 1.0.8. The following exception occurs if slide fast.
```
java.lang.IndexOutOfBoundsException: Invalid index 2, size is 2
                                                     at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                     at java.util.ArrayList.get(ArrayList.java:308)
                                                     at android.support.v4.view.ViewPager.getChildDrawingOrder(ViewPager.java:828)
                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2166)
                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                     at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
                                                     at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
                                                     at android.app.Activity.dispatchTouchEvent(Activity.java:2771)
                                                     at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71)
                                                     at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
                                                     at android.view.View.dispatchPointerEvent(View.java:9520)
                                                     at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4238)
                                                     at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4104)
                                                     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3650)
                                                     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3703)
                                                     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3669)
                                                     at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3795)
                                                     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3677)
                                                     at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3852)
                                                     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3650)
                                                     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3703)
                                                     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3669)
                                                     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3677)
                                                     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3650)
                                                     at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5932)
                                                     at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5906)
                                                     at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5867)
                                                     at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6035)
                                                     at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                     at android.os.MessageQueue.nativePollOnce(Native Method)
                                                     at android.os.MessageQueue.next(MessageQueue.java:323)
                                                     at android.os.Looper.loop(Looper.java:135)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5422)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

```

**Comment by ValeryGes** [comment]
Hi, @louisyonge, thank you for your feedback!

We will check this issue and fix it in next release, can you attach your xml and java code where you using library for reproducing this issue?

With best regards, Cleveroad team.

**Comment by louisyonge** [comment]
@ValeryGes Some codes. Hope it helps. Best!

class StartPageActivity

```
  private void startTutor() {
        boolean firstTime = (boolean) (SharePreferenceUtils.getParam(this, ConstanConfig.PF_FIRST_RUN, true));
        int[] mPagesColors = new int[]{
                ContextCompat.getColor(this, R.color.tourBackground),
                ContextCompat.getColor(this, R.color.tourBackground),
                ContextCompat.getColor(this, R.color.tourBackground),
                ContextCompat.getColor(this, R.color.tourBackground)
        };
        if (firstTime) {
            final TutorialOptions tutorialOptions = TutorialFragment.newTutorialOptionsBuilder(this)
                    .setTutorialPageProvider(getProvider())
                    .setPagesColors(mPagesColors)
                    .setUseInfiniteScroll(false)
                    .setPagesCount(4)
                    .setOnSkipClickListener((view -> startMain()))
                    .build();
            FragmentManager manager = getFragmentManager();
            final TutorialFragment tutorialFragment = TutorialFragment.newInstance(tutorialOptions);
            manager.beginTransaction()
                    .replace(R.id.frgContainer, tutorialFragment)
                    .commitAllowingStateLoss();
      //      SharePreferenceUtils.setParam(this, ConstanConfig.PF_FIRST_RUN, false);
        } else {
            startMain();
        }

...

 private TutorialPageOptionsProvider getProvider() {
        final TutorialPageOptionsProvider tutorialPageOptionsProvider = position -> {
            @LayoutRes int pageLayoutResId;
            TransformItem[] tutorialItems;
            switch (position) {
                case 0: {
                    pageLayoutResId = R.layout.fragment_tutor0;
                    tutorialItems = new TransformItem[]{
                            TransformItem.create(R.id.tv01, Direction.LEFT_TO_RIGHT, 0.1f),
                            TransformItem.create(R.id.tvt02, Direction.LEFT_TO_RIGHT, 0.4f),
                            TransformItem.create(R.id.tvt03, Direction.LEFT_TO_RIGHT, 0.2f),
                            TransformItem.create(R.id.img1, Direction.LEFT_TO_RIGHT, 0.2f),
                            TransformItem.create(R.id.img2, Direction.LEFT_TO_RIGHT, 0.2f),
                            TransformItem.create(R.id.img3, Direction.RIGHT_TO_LEFT, 0.1f),
                            TransformItem.create(R.id.img4, Direction.LEFT_TO_RIGHT, 0.3f),
                            TransformItem.create(R.id.img5, Direction.RIGHT_TO_LEFT, 0.4f),
                            TransformItem.create(R.id.img6, Direction.LEFT_TO_RIGHT, 0.5f)
                    };
                    break;
                }
                case 1: {
                    pageLayoutResId = R.layout.fragment_tutor1;
                    tutorialItems = new TransformItem[]{
                            TransformItem.create(R.id.tv01, Direction.RIGHT_TO_LEFT, 0.1f),
                            TransformItem.create(R.id.tv02, Direction.LEFT_TO_RIGHT, 0.1f),
                            TransformItem.create(R.id.img1, Direction.LEFT_TO_RIGHT, 0.3f),
                            TransformItem.create(R.id.img2, Direction.RIGHT_TO_LEFT, 0.2f),
                            TransformItem.create(R.id.img3, Direction.RIGHT_TO_LEFT, 0.15f)
                    };
                    break;
                }
                case 2: {
                    pageLayoutResId = R.layout.fragment_tutor2;
                    tutorialItems = new TransformItem[]{
                            TransformItem.create(R.id.tv01, Direction.LEFT_TO_RIGHT, 0.8f),
                            TransformItem.create(R.id.img1, Direction.RIGHT_TO_LEFT, 0.07f)
                    };
                    break;
                }
                case 3: {
                    pageLayoutResId = R.layout.fragment_tutor3;
                    tutorialItems = new TransformItem[]{
                            TransformItem.create(R.id.tv01, Direction.LEFT_TO_RIGHT, 0.1f),
                            TransformItem.create(R.id.img1, Direction.RIGHT_TO_LEFT, 0.7f)
                    };
                    break;
                }
                case 4: {
                    pageLayoutResId = R.layout.fragment_tutor4;
                    tutorialItems = new TransformItem[]{
                            TransformItem.create(R.id.tv01, Direction.LEFT_TO_RIGHT, 0.2f),
                            TransformItem.create(R.id.img1, Direction.RIGHT_TO_LEFT, 0.07f)
                    };
                    break;
                }
                default: {
                    throw new IllegalArgumentException("Unknown position: " + position);
                }
            }
            return PageOptions.create(pageLayoutResId, position, tutorialItems);
        };
        return tutorialPageOptionsProvider;
    }
```
TutoringFragment
```
public class TutoringFragment extends Fragment {
    public TutoringFragment() {
        // Required empty public constructor
    }
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        return inflater.inflate(R.layout.fragment_tutor0, container, false);
    }
    @Override
    public void onActivityCreated(@Nullable Bundle savedInstanceState) {
        super.onActivityCreated(savedInstanceState);
    }
}
```

**Comment by muhannadrsaad** [comment]
I encountered the same problem.

**Comment by muhannadrsaad** [comment]
I had fix it, but for performance wise it's not good if you have too many fragments to show

1. go to class TutorialImpl
2. onViewCreated method add below line after setAdapter.
   **mViewPager.setOffscreenPageLimit(mTutorialOptions.getPagesCount()-1);**

**Comment by efraespada** [comment]
👎 At the beginning `tutorialFragment.getViewPager()` returns `null`:

```java
final TutorialFragment tutorialFragment = TutorialFragment.newInstance(tutorialOptions);
getFragmentManager()
    .beginTransaction()
    .replace(R.id.container, tutorialFragment)
    .commit();

tutorialFragment.getViewPager().setOffscreenPageLimit(ACTUAL_PAGES_COUNT);      // boom
```

:ok_hand: Wait for `ViewPager` to be ready and use setOffscreenPageLimit:
```java
final TutorialFragment tutorialFragment = TutorialFragment.newInstance(tutorialOptions);
getFragmentManager()
    .beginTransaction()
    .replace(R.id.container, tutorialFragment)
    .commit();

Handler handler = new Handler();
Runnable runnable = new Runnable() {
    @Override
    public void run() {
        tutorialFragment.getViewPager().setOffscreenPageLimit(ACTUAL_PAGES_COUNT);
    }
};
handler.postDelayed(runnable, 1000);
```

**Comment by ghost** [comment]
+1 same issue on my env

**Comment by ricardochen** [comment]
efraespada solution worked for me.

**Comment by VadimHalimendikCr** [comment]
Hello! We fixed this bug in the latest version of this library.
Best regards Cleveroad team.

**Comment by georgeRCluj** [comment]
Hi, has anyone else encountered the same issue again?
