### ISSUE TITLE
 java.lang.NullPointerException: Attempt to get length of null array at com.cleveroad.slidingtutorial.PageImpl.onDestroyView

### ISSUE THREAD

**Issue by exequielc** [Cleveroad/slidingtutorial-android#60]
Question on **StackOverflow** http://stackoverflow.com/questions/43987164/unable-to-destroy-activity-with-slidingtutorial-library

`
NullPointerException for chess.vendo
                                                   java.lang.NullPointerException: Attempt to get length of null array
                                                       at com.cleveroad.slidingtutorial.PageImpl.onDestroyView(PageImpl.java:71)
                                                       at com.cleveroad.slidingtutorial.PageFragment.onDestroyView(PageFragment.java:73)
                                                       at android.app.Fragment.performDestroyView(Fragment.java:2570)
                                                       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1061)
                                                       at android.app.FragmentManagerImpl.detachFragment(FragmentManager.java:1351)
                                                       at android.app.BackStackRecord.run(BackStackRecord.java:798)
                                                       at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1580)
                                                       at android.app.FragmentManagerImpl$1.run(FragmentManager.java:483)
                                                       at android.os.Handler.handleCallback(Handler.java:751)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)`

**Comment by Iojjj** [comment]
Please provide the code of your `ContactoSecondFragment`, `ContactoFirstragment` and `ContactoThirdFragment`. If it possible, create a repo with minimal code that allows to reproduce this issue.

**Comment by gajicm93** [comment]
This just started happening to me too..

@exequielc Ok found the issue, I forgot to call super.OnCreateView from my PageSupportFragment imeplementation..
