### ISSUE TITLE
support for save instance state

### ISSUE THREAD

**Issue by v-mas** [Cleveroad/slidingtutorial-android#66]
```
AndroidRuntime: FATAL EXCEPTION: main
AndroidRuntime: Process: com.cleveroad.tutorialsample, PID: 26152
AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.cleveroad.tutorialsample/com.cleveroad.slidingtutorial.sample.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.cleveroad.slidingtutorial.TutorialOptions.getPagesCount()' on a null object reference
AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2316)
AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2376)
AndroidRuntime:        at android.app.ActivityThread.access$800(ActivityThread.java:147)
AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1281)
AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
AndroidRuntime:        at android.os.Looper.loop(Looper.java:135)
AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5253)
AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
AndroidRuntime:        at java.lang.reflect.Method.invoke(Method.java:372)
AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.cleveroad.slidingtutorial.TutorialOptions.getPagesCount()' on a null object reference
AndroidRuntime:        at com.cleveroad.slidingtutorial.TutorialImpl$TutorialAdapterImpl.getCount(TutorialImpl.java:281)
AndroidRuntime:        at com.cleveroad.slidingtutorial.TutorialFragment$TutorialAdapter.getCount(TutorialFragment.java:292)
AndroidRuntime:        at android.support.v4.view.ViewPager.setAdapter(ViewPager.java:526)
AndroidRuntime:        at com.cleveroad.slidingtutorial.TutorialImpl.onViewCreated(TutorialImpl.java:97)
AndroidRuntime:        at com.cleveroad.slidingtutorial.TutorialFragment.onViewCreated(TutorialFragment.java:152)
AndroidRuntime:        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:908)
AndroidRuntime:        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
AndroidRuntime:        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1049)
AndroidRuntime:        at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1869)
AndroidRuntime:        at android.app.Activity.performCreateCommon(Activity.java:5970)
AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:5977)
AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2269)
AndroidRuntime:        ... 10 more
```

just enable "don't keep activities" and try minimize/maximize sample app

**Comment by VadimHalimendikCr** [comment]
Thanks you for using our library. I think it be fix in next version.
With best regards Cleveroad team.
