### ISSUE TITLE
NullPointerException crash in getCount

### ISSUE THREAD

**Issue by tsoumalis** [Cleveroad/slidingtutorial-android#68]
Hello,

There is a crash that occurs randomly from devices and I see it on Crashlytics. 

```
Caused by java.lang.NullPointerException

Attempt to invoke virtual method 'int com.cleveroad.slidingtutorial.q.c()' on a null object reference

com.cleveroad.slidingtutorial.TutorialImpl$TutorialAdapterImpl.getCount (TutorialImpl.java:281)
com.cleveroad.slidingtutorial.TutorialSupportFragment$TutorialAdapter.getCount (TutorialSupportFragment.java:285)
android.support.v4.view.ViewPager.setAdapter (ViewPager.java:526)
com.cleveroad.slidingtutorial.TutorialImpl.onViewCreated (TutorialImpl.java:97)
com.cleveroad.slidingtutorial.TutorialSupportFragment.onViewCreated (TutorialSupportFragment.java:146)
android.support.v4.app.FragmentManagerImpl.moveToState (FragmentManager.java:1439)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:832)
```

**Comment by RedFish** [comment]
Same here... :/ Any idea how to solve it?

Stacktrace:

> Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int com.cleveroad.slidingtutorial.TutorialOptions.getPagesCount()' on a null object reference
       at com.cleveroad.slidingtutorial.TutorialImpl$TutorialAdapterImpl.getCount(TutorialImpl.java:312)
       at com.cleveroad.slidingtutorial.TutorialFragment$TutorialAdapter.getCount(TutorialFragment.java:302)
       at android.support.v4.view.ViewPager.setAdapter(ViewPager.java:526)
       at com.cleveroad.slidingtutorial.TutorialImpl.onViewCreated(TutorialImpl.java:107)
       at com.cleveroad.slidingtutorial.TutorialFragment.onViewCreated(TutorialFragment.java:157)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:994)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1157)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1139)
       at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1962)
       at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:152)
       at android.app.Activity.performCreateCommon(Activity.java:6360)
       at android.app.Activity.performCreate(Activity.java:6370)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2404)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2511)
       at android.app.ActivityThread.access$900(ActivityThread.java:165)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1375)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:150)
       at android.app.ActivityThread.main(ActivityThread.java:5621)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

**Comment by VadimHalimendikCr** [comment]
First of all thank you for using our library. I think it be fix in next version.
With best regards Cleveroad team.
